# Author/Blog Setup
name: new Chad()
description: A Blog About Code
author:
  name: Chad Engler
  email: chad@pantherdev.com

# Page setup
permalink: pretty
baseurl:
url: //englercj.github.io
encoding: UTF-8
excerpt_separator: <!--more-->

paginate: 5
paginate_path: "page:num"
quote:
  name: Albert Einstein
  content: We can’t solve problems by using the same kind of thinking we used when we created them.

# Markdown settings
markdown: kramdown

# Syntax Highlighting
highlighter: rouge

# Approved github jekyll plugins
gems:
  - jekyll-sitemap
  - jemoji

# Ignore files meant for building
exclude:
  - .bowerrc
  - .bundle
  - .ruby-version
  - bower.json
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json

# Analytics
analytics:
  google: UA-27838577-3

sharing:
  twitter: rolnaaba
  disqus: newchad

# Social links
social:
  github: englercj
  # facebook: chad.engler.5
  twitter: rolnaaba
  linkedin: chad-engler
  rss: /rss.xml